# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('initial', 'Ny'), ('open', 'Åben'), ('closed', 'Lukket')], default='initial', max_length=20),
        ),
    ]
