# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 11:54
from __future__ import unicode_literals

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_game_mode'),
    ]

    operations = [
        migrations.DeleteModel(name='Submission'),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Profile')),
            ],
            options={
                'ordering': ['game', 'profile', 'created_time'],
                'verbose_name': 'gæt',
                'verbose_name_plural': 'gæt',
            },
        ),
        migrations.CreateModel(
            name='SubmissionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Option')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Slot')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.Submission')),
            ],
            options={
                'ordering': ['submission', 'slot'],
                'verbose_name': 'gætindgang',
                'verbose_name_plural': 'gætindgange',
            },
        ),
        migrations.AlterUniqueTogether(
            name='submissionslot',
            unique_together=set([('submission', 'slot')]),
        ),
    ]
